name: Build image

on:
  push:
    branches: [ main ]
env:
  IMAGE_ID: "ghcr.io/megathorx/nginx-php" 

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
    
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.5.0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images for 7.4
        uses: docker/build-push-action@v4.0.0
        with:
          context: "{{defaultContext}}:."
          file: "7.4/Dockerfile"
          labels: "runnumber=${GITHUB_RUN_ID}"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: "${{ env.IMAGE_ID }}:7.4"
      
      - name: Build and push Docker images for 8.0
        uses: docker/build-push-action@v4.0.0
        with:
          context: "{{defaultContext}}:."
          file: "8.0/Dockerfile"
          labels: "runnumber=${GITHUB_RUN_ID}"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: "${{ env.IMAGE_ID }}:8.0"
      
      - name: Build and push Docker images for 8.1
        uses: docker/build-push-action@v4.0.0
        with:
          context: "{{defaultContext}}:."
          file: "8.1/Dockerfile"
          labels: "runnumber=${GITHUB_RUN_ID}"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: "${{ env.IMAGE_ID }}:8.1"
      
      - name: Build and push Docker images for 8.2
        uses: docker/build-push-action@v4.0.0
        with:
          context: "{{defaultContext}}:."
          file: "8.2/Dockerfile"
          labels: "runnumber=${GITHUB_RUN_ID}"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: "${{ env.IMAGE_ID }}:8.2,${{ env.IMAGE_ID }}:latest"
