name: Build image

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: nginx-php
  
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Export image id as environment variable
        run: |
          export IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

      - name: Build image php 7.4
        run: docker build . --file 7.4/Dockerfile --tag $IMAGE_ID:7.4 --label "runnumber=${GITHUB_RUN_ID}"

      - name: Build image php 8.2
        run: docker build . --file 8.0/Dockerfile --tag $IMAGE_ID:8.0 --label "runnumber=${GITHUB_RUN_ID}"

      - name: Build image php 8.1
        run: docker build . --file 8.1/Dockerfile --tag $IMAGE_ID:8.1 --label "runnumber=${GITHUB_RUN_ID}"

      - name: Build image php 8.2
        run: docker build . --file 8.2/Dockerfile --tag $IMAGE_ID:8.2 --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag $IMAGE_ID:8.2 $IMAGE_ID:latest
          docker push $IMAGE_ID:7.4
          docker push $IMAGE_ID:8.0
          docker push $IMAGE_ID:8.1
          docker push $IMAGE_ID:8.2
          docker push $IMAGE_ID:latest
